/* Generated by re2c 3.1 on Fri Mar 21 12:33:59 2025 */
// re2c $INPUT -o $OUTPUT -i --case-ranges
#include <assert.h>

int lex(const char *s) {
    const char *YYCURSOR = s, *YYMARKER;
    
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy3;
		default: goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
	{ return 1; }
yy3:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy4;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy2;
	}
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy7;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy5:
	YYCURSOR = YYMARKER;
	goto yy2;
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
			add_mtag(mt, @@, YYCURSOR);(yytm2);
			goto yy8;
		case ']':
			add_mtag(mt, @@, YYCURSOR);(yytm3);
			add_mtag(mt, @@, YYCURSOR);(yytm2);
			goto yy9;
		default: goto yy5;
	}
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy10;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy11;
		case ']':
			add_mtag(mt, @@, YYCURSOR);(yytm3);
			goto yy9;
		default: goto yy5;
	}
yy9:
	++YYCURSOR;
	name_end = yytm1;
	amount_st = yytm2;
	amount_end = yytm3;
	{ return 0; }
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy12;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy13;
		case ']':
			add_mtag(mt, @@, YYCURSOR);(yytm3);
			goto yy9;
		default: goto yy5;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy14;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy15;
		case ']':
			add_mtag(mt, @@, YYCURSOR);(yytm3);
			goto yy9;
		default: goto yy5;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy16;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy17;
		case ']':
			add_mtag(mt, @@, YYCURSOR);(yytm3);
			goto yy9;
		default: goto yy5;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy18;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy19;
		case ']':
			add_mtag(mt, @@, YYCURSOR);(yytm3);
			goto yy9;
		default: goto yy5;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy20;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy21;
		case ']':
			add_mtag(mt, @@, YYCURSOR);(yytm3);
			goto yy9;
		default: goto yy5;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy22;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy23;
		case ']':
			add_mtag(mt, @@, YYCURSOR);(yytm3);
			goto yy9;
		default: goto yy5;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy24;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9': goto yy25;
		case ']':
			add_mtag(mt, @@, YYCURSOR);(yytm3);
			goto yy9;
		default: goto yy5;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy26;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
		case ']':
			add_mtag(mt, @@, YYCURSOR);(yytm3);
			goto yy9;
		default: goto yy5;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy27;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy28;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy29;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy30;
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
		case '[':
			add_mtag(mt, @@, YYCURSOR);(yytm1);
			goto yy6;
		default: goto yy5;
	}
}

}

int main() {
    assert(lex("aaaaaaaaaaaaaa[1]") == 0);
    return 0;
}

// name_pt = [a-zA-Z][a-zA-Z0-9]{0,15};
// amount_pt = [0-9]{0,9};
// lexem = "-"?[0-9]+;