/* Generated by re2c 3.1 on Fri Mar 21 12:15:12 2025 */
// re2c $INPUT -o $OUTPUT -i --case-ranges
#include <assert.h>

int lex(const char *s) {
    const char *YYCURSOR = s, *YYMARKER;
    
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy3;
		default: goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
	{ return 1; }
yy3:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy4;
		case '[': goto yy6;
		default: goto yy2;
	}
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy7;
		case '[': goto yy6;
		default: goto yy5;
	}
yy5:
	YYCURSOR = YYMARKER;
	goto yy2;
yy6:
	++YYCURSOR;
	{ return 0; }
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy8;
		case '[': goto yy6;
		default: goto yy5;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy9;
		case '[': goto yy6;
		default: goto yy5;
	}
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy10;
		case '[': goto yy6;
		default: goto yy5;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy11;
		case '[': goto yy6;
		default: goto yy5;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy12;
		case '[': goto yy6;
		default: goto yy5;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy13;
		case '[': goto yy6;
		default: goto yy5;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy14;
		case '[': goto yy6;
		default: goto yy5;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy15;
		case '[': goto yy6;
		default: goto yy5;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy16;
		case '[': goto yy6;
		default: goto yy5;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy17;
		case '[': goto yy6;
		default: goto yy5;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy18;
		case '[': goto yy6;
		default: goto yy5;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy19;
		case '[': goto yy6;
		default: goto yy5;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0' ... '9':
		case 'A' ... 'Z':
		case 'a' ... 'z': goto yy20;
		case '[': goto yy6;
		default: goto yy5;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
		case '[': goto yy6;
		default: goto yy5;
	}
}

}

int main() {
    assert(lex("aAAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaa1c[") == 0);
    return 0;
}

// name_pt = [a-zA-Z][a-zA-Z0-9]{0,15};
// amount_pt = [0-9]{0,9};
// lexem = "-"?[0-9]+;